apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
#- connectors-svc.yaml
#- connectors-cm.yaml
#- connectors-deployment.yaml
- SVC_Cammnuda-edit-Rolebinding.yaml
#- route.yaml
- assign-roles.yaml
helmCharts:
- name: camunda-platform
  repo: https://helm.camunda.io
  version: 10.0.4
  releaseName: camunda-platform
  namespace: camunda
  valuesFile: values.yaml
patchesStrategicMerge:
- es-statefulset.yaml
- key-statefulset.yaml
- pg-statefulset.yaml