apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestProxy
metadata:
  name: kafkarestproxy
  namespace: confluent-kafka
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  dependencies:
    schemaRegistry:
      url: http://schemaregistry.confluent.svc.cluster.local:8081
  image:
    application: docker.io/confluentinc/cp-kafka-rest:7.4.0
    init: docker.io/confluentinc/confluent-init-container:2.6.0
  tls:
    secretRef: kafka-tls
    ignoreTrustStoreConfig: false
  externalAccess:
    route:
      domain: apps.dev-nonpci-appdb.npnbank.local
    type: route  
  replicas: 2
  podTemplate:
    podSecurityContext: {}