apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - route.yaml
  - secrets.yaml
helmCharts:
- name: unleash
  repo: https://docs.getunleash.io/helm-charts
  version: 5.1.6
  releaseName: unleash-be
  namespace: unleash-be
  valuesFile: values.yaml