---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unleash-be
  namespace: unleash-be
  #annotations:
   # argocd.argoproj.io/sync-options: Prune=false
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: unleash-be
  data:
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: unleash-be
      property: postgres_password
  - secretKey: UNLEASH_PASSWORD
    remoteRef:
      key: unleash-be
      property: unleash_password
