apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: isva
spec:
  data:
  - secretKey: clientSecret
    remoteRef:
      key: alpha/dev-nonpci-appdb/isva
      property: clientSecret
