apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fobmp
spec:
  data:
  - secretKey: fobMpClientSecret
    remoteRef:
      key: alpha/dev-nonpci-appdb/fobmp
      property: fobMpClientSecret
