apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: arb
spec:
  data:
    - secretKey: arb-private-key
      remoteRef:
        key: alpha/dev-nonpci-appdb/arb
        property: arb-private-key
