apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: neotek
spec:
  data:
    - secretKey: neotek-client-secret
      remoteRef:
        key: alpha/dev-nonpci-appdb/neotek
        property: neotek-client-secret
    - secretKey: neotek-key-store-password
      remoteRef:
        key: alpha/dev-nonpci-appdb/neotek
        property: neotek-key-store-password
    - secretKey: neotek-trust-store-password
      remoteRef:
        key: alpha/dev-nonpci-appdb/neotek
        property: neotek-trust-store-password