apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: alpha
  name: alpha
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
---
kind: ServiceMeshMember
apiVersion: maistra.io/v1
metadata:
  name: default
  namespace: alpha
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  controlPlaneRef:
    name: basic
    namespace: service-mesh
