apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: Prune=false
spec:
  provider:
    vault:
      server: https://vault.apps.prod-nonpci-shared.nrapp.cloud
      path: alpha
      version: v2
      caProvider:
        key: ca.crt
        name: vault-auth-token-rx6zv
        namespace: vault
        type: Secret
      auth:
        kubernetes:
          mountPath: prod-nonpci-appdb
          role: alpha
          serviceAccountRef:
            name: vault-auth
            namespace: vault
