apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: router-certs-pca
  namespace: openshift-ingress
spec:
  data:
  - secretKey: ca.crt
    remoteRef:
      key: shared/certificate
      property: ca.crt
  - secretKey: tls.crt
    remoteRef:
      key: shared/certificate
      property: tls.crt
  - secretKey: tls.key
    remoteRef:
      key: shared/certificate
      property: tls.key
