apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    machine.openshift.io/memoryMb: '16384'
    machine.openshift.io/vCPU: '4'
    argocd.argoproj.io/sync-wave: "-1"
  name: postgresql-wokers
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: placeholder
spec:
  replicas: 3
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: placeholder
      machine.openshift.io/cluster-api-machineset: placeholder-postgresql
  template:
    metadata:
      labels:
        croatia-role: postgresql
        machine.openshift.io/cluster-api-cluster: placeholder
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: placeholder-postgresql
    spec:
      lifecycleHooks: {}
      metadata:
        labels:
          croatia-role: postgresql
      providerSpec:
        value:
          numCoresPerSocket: 1
          diskGiB: 120
          snapshot: ''
          userDataSecret:
            name: worker-user-data
          memoryMiB: 16384
          credentialsSecret:
            name: vsphere-cloud-credentials
          network:
            devices:
              - networkName: placeholder
          metadata:
            creationTimestamp: null
          numCPUs: 4
          kind: VSphereMachineProviderSpec
          workspace:
            datacenter: oci-w01dc
            datastore: vsanDatastore
            folder: /oci-w01dc/vm/placeholder
            resourcePool: /oci-w01dc/host/oci01-w01-consolidated01/Resources
            server: vcenter-development.sddc.jed.oci.oraclecloud.com
          template: placeholder-aaaaa-rhcos
          apiVersion: machine.openshift.io/v1beta1
