apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
#- assign-roles.yaml
#- camunda-postgres-sts.yaml
#- camunda-keycloak-sts.yaml
#- elasticsearch-sts.yaml
#- route.yaml
- assign-roles.yaml
helmCharts:
- name: camunda-platform
  repo: https://helm.camunda.io
  version: 8.1.6
  releaseName: camunda-platform
  namespace: camunda-mod
  valuesFile: values.yaml
patches:
- target:
    kind: Secret
  patch: |-
    $patch: delete
    apiVersion: v1
    kind: Secret
    metadata:
      name: any
- path: key-statefulset.yaml
- path: pg-statefulset.yaml
- path: es-statefulset.yaml
