kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: SVC_Cammnuda-edit
  namespace: camunda-mod
  annotations:
    argocd.argoproj.io/sync-wave: "2"
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: akamaeldin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit