apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nexus-root-password
  namespace: nexus-repository 
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: nexus-root-password
  data:
  - secretKey: password
    remoteRef:
      key: nexus
      property: password
