apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: nexus-repository
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: v1.24
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: v1.24
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    openshift.io/description: ""
    openshift.io/display-name: ""
    openshift.io/requester: kube:admin
    openshift.io/sa.scc.mcs: s0:c34,c4
    openshift.io/sa.scc.supplemental-groups: 1001130000/10000
    openshift.io/sa.scc.uid-range: 1001130000/10000
  name: nexus-repository
spec:
  finalizers:
  - kubernetes