apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database
spec:
  data:
  - secretKey: mc-password
    remoteRef:
      key: alpha/development/database
      property: mc-password
  - secretKey: sc-password
    remoteRef:
      key: alpha/development/database
      property: sc-password
  - secretKey: sl-password
    remoteRef:
      key: alpha/development/database
      property: sl-password
  - secretKey: cb-event-adapter-password
    remoteRef:
      key: alpha/development/database
      property: cb-event-adapter-password
