apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-shared
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: Prune=false
spec:
  provider:
    vault:
      server: https://vault-prod.apps.prod-nonpci-shared.nrapp.cloud
      path: shared
      namespace: root
      version: v2
      caProvider:
        key: ca.crt
        name: vault-ha-tls
        namespace: vault-client
        type: Secret
      auth:
        kubernetes:
          mountPath: dr-nonpci-appdb
          role: dr-nonpci-appdb-shared
          serviceAccountRef:
            name: vault-auth
            namespace: vault-client