
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
  namespace: service-mesh
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ingressgateway-ca-certs
  namespace: service-mesh
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  isCA: true
  commonName: istio-ingressgateway-ca-certs
  secretName: istio-ingressgateway-ca-certs
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  issuerRef:
    name: selfsigned
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-ca
  namespace: service-mesh
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  ca:
    secretName: istio-ingressgateway-ca-certs
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ingressgateway-certs
  namespace: service-mesh
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretName: istio-ingressgateway-certs
  subject:
    organizations:
      - projectcroatia
  commonName: placeholder
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
  dnsNames:
    - "*.placeholder"
  issuerRef:
    name: selfsigned-ca
    kind: Issuer
