apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: service-mesh
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  gateways:
    egress:
      enabled: true
      runtime:
        deployment:
          replicas: 3
        pod:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - values:
                          - infra
                        key: croatia-role
                        operator: In
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - values:
                          - istio-ingressgateway
                        key: app
                        operator: In
                  topologyKey: kubernetes.io/hostname
          tolerations:
            - effect: NoSchedule
              key: croatia-role/infra
              operator: Exists
    enabled: true
    ingress:
      enabled: true
      ingress: true
      service:
        type: NodePort
        ports:
        - name: status-port
          port: 15021
          protocol: TCP
          targetPort: 15021
        - name: http2
          port: 80
          protocol: TCP
          targetPort: 8080
        - name: https
          port: 443
          protocol: TCP
          targetPort: 8443
          nodePort: 30443
        - name: tls
          port: 15443
          protocol: TCP
          targetPort: 15443
      runtime:
        deployment:
          replicas: 3
        pod:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - values:
                          - infra
                        key: croatia-role
                        operator: In
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - values:
                          - istio-ingressgateway
                        key: app
                        operator: In
                  topologyKey: kubernetes.io/hostname
          tolerations:
            - effect: NoSchedule
              key: croatia-role/infra
              operator: Exists
    openshiftRoute:
      enabled: false
  policy:
    type: Istiod
  profiles:
    - default
  proxy:
    injection:
      autoInject: true
  telemetry:
    type: Istiod
  tracing:
    sampling: 10000
    type: Jaeger
  version: v2.1
