apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fobmp
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: fobmp
  data:
  - secretKey: fobMpClientSecret
    remoteRef:
      key: alpha/placeholder/fobmp
      property: fobMpClientSecret
