apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crm
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: crm
  data:
  - secretKey: mc-crm-adapter-password
    remoteRef:
      key: alpha/development/crm
      property: mc-crm-adapter-password