apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cms
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: cms
  data:
    - secretKey: file-api-key
      remoteRef:
        key: alpha/development/cms
        property: file-api-key