apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: apple
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: apple
  data:
    - secretKey: pass-file-appreciation-password
      remoteRef:
        key: alpha/placeholder/apple
        property: pass-file-appreciation-password