apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: temenos
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: temenos
  data:
  - secretKey: password
    remoteRef:
      key: alpha/placeholder/temenos
      property: password