apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: marketplace
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: marketplace
  data:
  - secretKey: sl-marketplace-client-secret
    remoteRef:
      key: alpha/placeholder/marketplace
      property: secret
  - secretKey: fob-private-key
    remoteRef:
      key: alpha/placeholder/marketplace
      property: fob-private-key
  - secretKey: fob-public-key
    remoteRef:
      key: alpha/placeholder/marketplace
      property: fob-public-key
  - secretKey: key-store-password
    remoteRef:
      key: alpha/placeholder/marketplace
      property: key-store-password
  - secretKey: trust-store-password
    remoteRef:
      key: alpha/placeholder/marketplace
      property: trust-store-password
  - secretKey: sl-marketplace-yakeen-client-secret
    remoteRef:
      key: alpha/placeholder/marketplace
      property: yakeen-secret