apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: camunda
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: camunda
  data:
  - secretKey: operate-client-secret
    remoteRef:
      key: alpha/placeholder/camunda
      property: operate-client-secret
  - secretKey: tasklist-client-secret
    remoteRef:
      key: alpha/placeholder/camunda
      property: tasklist-client-secret
  - secretKey: zeebe-client-secret
    remoteRef:
      key: alpha/placeholder/camunda
      property: zeebe-client-secret