apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ips
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: ips
  data:
  - secretKey: ips_gateway_secret
    remoteRef:
      key: alpha/dev-nonpci-appdb/ips
      property: ips_gateway_secret
  - secretKey: ips_cb_client_secret
    remoteRef:
      key: alpha/dev-nonpci-appdb/ips
      property: ips_cb_client_secret
