apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nafath
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: nafath
  data:
  - secretKey: nafath-client-secret
    remoteRef:
      key: alpha/placeholder/nafath
      property: nafath-client-secret