apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
#- externalsecrets.yaml
#- secrets.yaml
- route.yaml
helmCharts:
- name: jfrog-platform
  repo: https://artifactory.apps.prod-nonpci-shared.nrapp.cloud/artifactory/helm-virtual/
  version: 10.12.1
  releaseName: jfrog-platform
  namespace: artifactory
  valuesFile: values.yaml