apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bitbucket
  namespace: argocd-2-12-3
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: bitbucket
  data:
  - secretKey: ssh-key
    remoteRef:
      key: shared/jenkins-credentials
      property: ssh-key
  - secretKey: bitbucket-token
    remoteRef:
      key: shared/jenkins-credentials
      property: bitbucket-token