apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- route.yaml
- externalsecret.yaml
- sso.yaml
helmCharts:
- name: argo-cd
  repo: https://argoproj.github.io
  version: 7.6.4
  releaseName: argocd
  namespace: argocd-2-12-3
  valuesFile: values.yaml