apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
spec:
  image: artifactory.apps.dev-nonpci-shared.npnbank.local/docker-local/argocd
  version: v2.6.7
  server:
    autoscale:
      enabled: false
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 125m
        memory: 128Mi
    route:
      enabled: false
    service:
      type: ''
    insecure: true
    host: argocd.apps.dev-nonpci-shared.npnbank.local
  grafana:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  notifications:
    enabled: false
  prometheus:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  initialSSHKnownHosts: {}
  resourceCustomizations: |
    Secret:
      ignoreDifferences: |
        jsonPointers:
        - /data/admin-password
        - /data/password
        - /data/repmgr-password
    ServiceAccount:
      ignoreDifferences: |
        jsonPointers:
        - /imagePullSecrets
    admissionregistration.k8s.io/MutatingWebhookConfiguration:
      ignoreDifferences: |
        jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/1/clientConfig/caBundle
        - /webhooks/2/clientConfig/caBundle
        - /webhooks/3/clientConfig/caBundle
        - /webhooks/4/clientConfig/caBundle
        - /webhooks/5/clientConfig/caBundle
        - /webhooks/6/clientConfig/caBundle
        - /webhooks/7/clientConfig/caBundle
        - /webhooks/8/clientConfig/caBundle
        - /webhooks/9/clientConfig/caBundle
        - /webhooks/10/clientConfig/caBundle
    admissionregistration.k8s.io/ValidatingWebhookConfiguration:
      ignoreDifferences: |
        jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/1/clientConfig/caBundle
        - /webhooks/2/clientConfig/caBundle
        - /webhooks/3/clientConfig/caBundle
        - /webhooks/4/clientConfig/caBundle
        - /webhooks/5/clientConfig/caBundle
        - /webhooks/6/clientConfig/caBundle
        - /webhooks/7/clientConfig/caBundle
        - /webhooks/8/clientConfig/caBundle
        - /webhooks/9/clientConfig/caBundle
        - /webhooks/10/clientConfig/caBundle
  applicationSet: {}
  rbac:
    policy: 'g, ArgoCDAdmins, role:admin'
  repo:
    resources:
      limits:
        cpu: '1'
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
  ha:
    enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  kustomizeBuildOptions: '--enable-helm --load-restrictor LoadRestrictionsNone'
  tls:
    ca: {}
  redis:
    image: 'docker.io/redis:7'
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  usersAnonymousEnabled: true
  controller:
    processors: {}
    resources:
      limits:
        cpu: '2'
        memory: 8Gi
      requests:
        cpu: '1'
        memory: 4Gi
    sharding: {}
  oidcConfig: |
    name: Keycloak
    issuer: https://keycloak-sso.apps.dev-nonpci-shared.npnbank.local/auth/realms/argocd
    clientID: argocd
    clientSecret: na
    requestedScopes: ["openid", "profile", "email", "groups"]
    skipAudienceCheckWhenTokenHasNoAudience: true
    rootCA: |
      -----BEGIN CERTIFICATE-----
      MIIFAzCCAuugAwIBAgIQJQvAgGggdZ1IUYPJ8VxWIDANBgkqhkiG9w0BAQsFADAU
      MRIwEAYDVQQDEwlBUkJDQVJvb3QwHhcNMjMwMzMwMjAxNTIxWhcNNDgwMzMwMjAy
      NTE5WjAUMRIwEAYDVQQDEwlBUkJDQVJvb3QwggIiMA0GCSqGSIb3DQEBAQUAA4IC
      DwAwggIKAoICAQCwBXmyF0lcY0ffCw/bXx/YPY7ycUJUVdQAJHNEe/3fvFKKz9A9
      EPkM4dYdSGi7ZRzISXMNndjsB9ywdGTrh2mUPRIIeSImOCAMheUX0kLuLrDdUgE8
      dUXEQn/r9ZWomkwCw59x1VxvVRFN98n//02YrH81ae6Twv6ow3coojLsrFPtHw5I
      VcnbYrO20hU5Y8E06BjyDzkzeNd9//+zHrzG+pvrcJEaszTltQGDC3gzcbOBZIDh
      Olh3eflFdpcF3rn5awxAolUglpXqRy++jM9lcnCEv6ITswXLJJb724UHGJAUS/V0
      7U2NgnGA13r+RiHr7yf0xJtdMkb/hY9C036XTCLTQuQxHKasdi5uMfdLIux4dYBC
      H34etqCylifz1OfN1so/m88R0NtMb8YXd+VlVuyREIfLB4CBP/4VLiDbgMNBgfrN
      dghQQ5h6w8BEeKvuBFirRTDZaSXe8POFQBdHZKcqeZfRZqCbYnOsYo+rIEINkbFG
      TvwjE7RrPDLadOGf1A6QmELrY+EBNtr+Vl2kaV1QWFHCe4tzdTFZzUzG+UsVPp3u
      zQEZY1T0drpfw3g0le2fk8jek/IrC1r3AeVRFqrN/qkTJbD8X/DBsa/UbtHxU9TF
      Drlp3UENUhpbY41UMedb/Qztke54q07g+zKEdh6HRN0ZgHwd5NMbHySHsQIDAQAB
      o1EwTzALBgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUlfyg
      6Tps1WGAIIToNTtqryCxU6wwEAYJKwYBBAGCNxUBBAMCAQAwDQYJKoZIhvcNAQEL
      BQADggIBAFo/Z8EY8RauF0U/5WMEFPg9oQixO3nufCkXLdVFlob07dztPudmKB+r
      QP02JrLPo03alaRKdEAwRlr1x+ssSF4DGolzP8qrZW+dqBL6bC6F+u8wBMdEwh35
      vXs/9U+VZJKAgejwBFlagRr5pt5SkvEgksZhZkdN329675A7xhCrHqbHYcNAQXIR
      ps6zb0CbskDMMKZQ01lzc/auIgtVkG4p82CQAQSLyuz4jbemNV+tjRyD2dk4SnLt
      51PV72VfCARdXUyiNsCvQKmdHkwy7T2u7QDRwHtwvBoZbCeEgEJNkVaV3F8svauE
      x3iZVEQ+CFNs4mXtwxLnhMmMUKnJn5s6637jWoeYfM9RvMj9EsjFrCPo5rc2bCco
      1QvhFSwugYAEoDTssrTqvoSoZDTPGXi63/xso0ORKz+aLlnauc1l2iQfjnElwrau
      OKnbGeuUdaLAzymB84oInf6VHhdqnl1G19a5eAZukCxuhkcULD/JZaO7rqwDkHwH
      R/7DfDPIJ2vKtl9XLEszmXP+Yjqor1CwPj27eqwjftdi67+TmBX3/LNn5OF4k/yU
      OaT2v1+HwSnueT6TOD6aAsXgUtdEMuOJ+98DrKBgcOnD2BadfBTAGWmUq3Xx9OET
      p6PsQ6BStv1bd85H0tbqdR+xM/oP4Td1n0KWGA8JFCPVXKEG+r3v
      -----END CERTIFICATE-----
