apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent-kafka
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  tls:
    secretRef: kafka-tls
    ignoreTrustStoreConfig: false
  image:
    application: artifactory.apps.prod-nonpci-shared.nrapp.cloud/docker/confluentinc/cp-enterprise-control-center:7.4.0
    init: artifactory.apps.prod-nonpci-shared.nrapp.cloud/docker/confluentinc/confluent-init-container:2.6.0
  dataVolumeCapacity: 100Gi
  externalAccess:
    route:
      domain: apps.dr-nonpci-appdb.nbank.local
    type: route  
  dependencies:
    schemaRegistry:
      url: https://schemaregistry.confluent.svc.cluster.local:8081
    ksqldb:
    - name: ksqldb
      url: https://ksqldb.confluent.svc.cluster.local:8088
    connect:
    - name: connect
      url:  https://connect.confluent.svc.cluster.local:8083
  podTemplate:
    podSecurityContext: {}
    resources:
      requests:
        cpu: "1"
        memory: "4Gi"
    probe:
      liveness:
        periodSeconds: 10
        failureThreshold: 5
        timeoutSeconds: 500