apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: schemaregistry
  namespace: confluent-kafka
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 2
  tls:
    secretRef: kafka-tls
    ignoreTrustStoreConfig: true
  image:
    application: artifactory.apps.prod-nonpci-shared.nrapp.cloud/docker/confluentinc/cp-schema-registry:7.4.0
    init: artifactory.apps.prod-nonpci-shared.nrapp.cloud/docker/confluentinc/confluent-init-container:2.6.0
  externalAccess:
    route:
      domain: apps.dr-nonpci-appdb.nbank.local
    type: route  
  podTemplate:
    podSecurityContext: {}