apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "app.name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "app.name" . }}-scc-clusterrole
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  - hostmount-anyuid
  - nonroot
  - hostnetwork-v2
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "app.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "app.name" . }}-scc-clusterrole
subjects:
- kind: ServiceAccount
  name: {{ template "app.name" . }}
