apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../alerting
- cluster-monitoring-config.yaml
- kasten-failed-jobs-alerts.yaml
patchesStrategicMerge:
- externalsecrets.yaml
