apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  title: Croatia Shared Services
  name: croatia-shared-services
spec:
  owner: platform
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:./vault
  title: Hashicorp Vault
  name: vault
spec:
  lifecycle: experimental
  owner: platform
  type: service
  system: croatia-shared-services
