apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-ent
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: dev-nonpci-appdb
          role: alpha
      namespace: microservices
      path: alpha
      caProvider:
        name: vault-ca-cert