kind: Namespace
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    kubernetes.io/metadata.name: kasten-io
    openshift.io/cluster-logging: "true"
    openshift.io/cluster-monitoring: "false"
  name: kasten-io
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: 'K10.v1alpha1.apik10.kasten.io,K10restore.v1alpha1.apik10.kasten.io'
    argocd.argoproj.io/sync-wave: "-2"
    argocd.argoproj.io/sync-options: Prune=false
  namespace: kasten-io
  name: kasten-io-operator
spec:
  targetNamespaces:
    - kasten-io
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/k10-kasten-operator-term-rhmp.kasten-io: ""
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: Prune=false
  name: k10-kasten-operator-term-rhmp
  namespace: kasten-io
spec:
  channel: stable
  installPlanApproval: Manual
  name: k10-kasten-operator-term-rhmp
  source: redhat-marketplace
  sourceNamespace: openshift-marketplace
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: Prune=false
  name: allow-openshift-monitoring
  namespace: kasten-io
  labels:
    app: k10
spec:
  podSelector:
    matchLabels:
      release: k10
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: openshift-user-workload-monitoring
    - ports:
        - protocol: TCP
          port: http
  policyTypes:
    - Ingress
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    k8s-app: kasten-io
  name: catalog
  namespace: kasten-io
spec:
  endpoints:
    - interval: 30s
      port: http
      scheme: http
  namespaceSelector:
    matchNames:
      - kasten-io
  selector:
    matchLabels:
      component: catalog
