apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: artifactory
  namespace: sso
spec:
  instanceSelector:
    matchLabels:
      app: sso
  realm:
    displayName: artifactory
    enabled: true
    id: artifactory
    realm: artifactory