apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: alerting
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            argo-cluster-role: primary
  template:
    metadata:
      name: '{{nameNormalized}}-alerting'
      namespace: argocd
      labels:
        environment: '{{nameNormalized}}'
    spec:
      destination:
        server: '{{server}}'
        namespace: alerting
      project: croatia-digital-platform
      source:
        path: 'overlays/{{nameNormalized}}/alerting'
        repoURL: 'ssh://git@bitbucket.projectcroatia.cloud/dig/croatia-components.git'
        targetRevision: HEAD
      syncPolicy: {}
