apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: alpha-apigateway
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            argo-cluster-type: dmz
  template:
    metadata:
      name: '{{nameNormalized}}-alpha-apigateway'
      namespace: argocd
      labels:
        environment: '{{nameNormalized}}'
        component: apigateway
    spec:
      destination:
        server: '{{server}}'
      project: alpha
      source:
        path: 'overlays/{{ nameNormalized }}'
        repoURL: 'ssh://git@bitbucket.projectcroatia.cloud/alpha/alpha-apigateway.git'
        targetRevision: HEAD
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true
