apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: camunda-platform
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            argo-cluster-type: alpha
            argo-cluster-role: primary
  template:
    metadata:
      name: '{{nameNormalized}}-camunda-platform'
      namespace: argocd
      labels:
        environment: '{{nameNormalized}}'
        component: alpha
    spec:
      destination:
        namespace: camunda
        server: '{{server}}'
      project: croatia-digital-platform
      source:
        path: 'overlays/{{nameNormalized}}/camunda-platform'
        repoURL: 'ssh://git@bitbucket.projectcroatia.cloud/dig/croatia-camunda.git'
        targetRevision: HEAD
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
