apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: unleash
  namespace: unleash
spec:
  host: unleash.apps.dev-nonpci-shared.npnbank.local
  to:
    kind: Service
    name: unleash
    weight: 100
  port:
    targetPort: 4242
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None