apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-encryption
  namespace: n8n
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: encryption-key
  data:
  - secretKey: N8N_ENCRYPTION_KEY
    remoteRef:
      key: n8n
      property: encryption-key
