apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-password
  namespace: n8n
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: redis-password
  data:
  - secretKey: REDIS_PASSWORD
    remoteRef:
      key: n8n
      property: redis-password
