apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: n8n
  name: n8n-pvc
  labels:
    app.kubernetes.io/name: n8n
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
