apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-main
  namespace: openshift-monitoring
spec:
  data:
  - secretKey: critical
    remoteRef:
      key: alpha/dev-nonpci-appdb/alerting
      property: critical-alerts-webhook
  - secretKey: default
    remoteRef:
      key: alpha/dev-nonpci-appdb/alerting
      property: default-alerts-webhook
  - secretKey: smarthost
    remoteRef:
      key: alpha/alpha-smtp-configurations
      property: smtp-smarthost
  - secretKey: smtp_authusername
    remoteRef:
      key: alpha/alpha-smtp-configurations
      property: smtp-auth-username
  - secretKey: smtp_authpassword
    remoteRef:
      key: alpha/alpha-smtp-configurations
      property: smtp-auth-password