---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unleash
  namespace: unleash
  #annotations:
   # argocd.argoproj.io/sync-options: Prune=false
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: unleash
  data:
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: unleash
      property: postgres_password
  - secretKey: UNLEASH_PASSWORD
    remoteRef:
      key: unleash
      property: unleash_password
