postgresql:
  primary:
    persistence:
      enabled: true
      size: 15Gi
    containerSecurityContext:
      runAsUser: 1001190000
    podSecurityContext:
      fsGroup: 1001190000
      runAsUser: 1001190000
  readReplicas:
    containerSecurityContext:
      runAsUser: 1001190000
    podSecurityContext:
      fsGroup: 1001190000
      runAsUser: 1001190000
  auth:
    existingSecret: unleash
    secretKeys:
      adminPasswordKey: POSTGRES_PASSWORD
      userPasswordKey: POSTGRES_PASSWORD
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: 17.0.0-debian-12-r3
    digest: ""
dbConfig:     
  useExistingSecret:
    name: unleash
    key: POSTGRES_PASSWORD
env:
  - name: UNLEASH_DEFAULT_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: unleash
        key: UNLEASH_PASSWORD
replicaCount: 2
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
resources:
 limits:
   cpu: 1000m
   memory: 1024Mi
 requests:
   cpu: 500m
   memory: 512Mi

    
 
