apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-ent
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: dev-dmz-ingress
      caProvider:
        name: vault-ca-cert