apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- namespace.yaml
- role.yaml
- rolebinding.yaml
- route.yaml
- secrets.yaml
- service.yaml
- serviceaccount.yaml
helmCharts:
- name: postgresql
  repo: https://charts.bitnami.com/bitnami
  version: 12.5.2
  releaseName: postgresql
  namespace: backstage
  valuesFile: postgres-values.yaml
