auth:
  existingSecret: backstage
rbac:
  create: true
  rules:
  - apiGroups:
    - security.openshift.io
    resourceNames:
    - nonroot
    - privileged
    resources:
    - securitycontextconstraints
    verbs:
    - use
serviceAccount:
  create: true
