---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage
  namespace: backstage
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: backstage
  data:
  - secretKey: postgres-password
    remoteRef:
      key: shared/backstage
      property: postgres-password
  - secretKey: app-config.production.yaml
    remoteRef:
      key: shared/backstage
      property: app-config.production.yaml
