apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: drahim
spec:
  data:
    - secretKey: drahim-client-secret
      remoteRef:
        key: alpha/uat-nonpci-appdb/drahim
        property: secret
