apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: complaint
spec:
  data:
    - secretKey: smtp-auth-password
      remoteRef:
        key: alpha/uat-nonpci-appdb/complaint
        property: smtp-auth-password
