apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cms
spec:
  data:
    - secretKey: file-api-key
      remoteRef:
        key: alpha/uat-nonpci-appdb/cms
        property: file-api-key