apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: router-certs-pca
  namespace: artifactory
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: router-certs-pca
    template:
      type: kubernetes.io/tls
  data:
  - secretKey: ca.crt
    remoteRef:
      key: shared/certificate
      property: ca.crt
  - secretKey: tls.crt
    remoteRef:
      key: shared/certificate
      property: tls.crt
  - secretKey: tls.key
    remoteRef:
      key: shared/certificate
      property: tls.key
