apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- externalsecrets.yaml
- namespace.yaml
- secrets.yaml
- route.yaml
- sso.yaml
- backup-volume.yaml
helmCharts:
- name: jfrog-platform
  repo: https://charts.jfrog.io
  version: 10.12.1
  releaseName: jfrog-platform
  namespace: artifactory
  valuesFile: values.yaml
patchesStrategicMerge:
- artifactory-statefulset.yaml