---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: artifactory-keys
  namespace: artifactory
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: artifactory-keys
  data:
  - secretKey: master-key
    remoteRef:
      key: shared/artifactory
      property: master-key
  - secretKey: join-key
    remoteRef:
      key: shared/artifactory
      property: join-key
  - secretKey: license
    remoteRef:
      key: shared/artifactory
      property: license
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: artifactory-ha-database-creds
  namespace: artifactory
type: Opaque
data:
  user: cG9zdGdyZXM=
  url: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXNxbC1oYS1wZ3Bvb2w6NTQzMi9hcnRpZmFjdG9yeQ==
