apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent-kafka
spec:
  replicas: 1
  image:
    application: docker.io/confluentinc/cp-enterprise-control-center:7.3.0
    init: docker.io/confluentinc/confluent-init-container:2.5.0
  dataVolumeCapacity: 100Gi
  dependencies:
    schemaRegistry:
      url: https://schemaregistry.confluent.svc.cluster.local:8081
    ksqldb:
    - name: ksqldb
      url: https://ksqldb.confluent.svc.cluster.local:8088
    connect:
    - name: connect
      url:  https://connect.confluent.svc.cluster.local:8083
  podTemplate:
    podSecurityContext: {}
    resources:
      requests:
        cpu: "1"
        memory: "4Gi"
    probe:
      liveness:
        periodSeconds: 10
        failureThreshold: 5
        timeoutSeconds: 500
