apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent-kafka
spec:
  replicas: 3
  image:
    application: docker.io/confluentinc/cp-server:7.3.0
    init: docker.io/confluentinc/confluent-init-container:2.5.0
  dataVolumeCapacity: 100Gi
  metricReporter:
    enabled: true
  podTemplate:
    podSecurityContext: {}
    resources:
      requests:
        cpu: "1"
        memory: "4Gi"
