apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestProxy
metadata:
  name: kafkarestproxy
  namespace: confluent-kafka
spec:
  dependencies:
    schemaRegistry:
      url: http://schemaregistry.confluent.svc.cluster.local:8081
  image:
    application: docker.io/confluentinc/cp-kafka-rest:7.3.0
    init: docker.io/confluentinc/confluent-init-container:2.5.0
  replicas: 2
  podTemplate:
    podSecurityContext: {}
