apiVersion: platform.confluent.io/v1beta1
kind: KsqlDB
metadata:
  name: ksqldb
  namespace: confluent-kafka
spec:
  replicas: 2
  image:
    application: docker.io/confluentinc/cp-ksqldb-server:7.3.0
    init: docker.io/confluentinc/confluent-init-container:2.5.0
  dataVolumeCapacity: 100Gi
  podTemplate:
    podSecurityContext: {}
