apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: schemaregistry
  namespace: confluent-kafka
spec:
  replicas: 2
  image:
    application: docker.io/confluentinc/cp-schema-registry:7.3.0
    init: docker.io/confluentinc/confluent-init-container:2.5.0
  podTemplate:
    podSecurityContext: {}
