apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- secrets.yaml
helmCharts:
- name: artifactory
  repo: https://charts.jfrog.io
  version: 107.55.2
  releaseName: artifactory
  namespace: artifactory
  valuesFile: values.yaml
