---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: artifactory
    istio-injection: disabled
  name: artifactory
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    argocd.argoproj.io/sync-options: Prune=false
---
kind: ServiceMeshMember
apiVersion: maistra.io/v1
metadata:
  name: default
  namespace: artifactory
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    argocd.argoproj.io/sync-options: Prune=false
spec:
  controlPlaneRef:
    name: basic
    namespace: service-mesh
