---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: artifactory
  namespace: artifactory
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: artifactory
  data:
  - secretKey: master-key
    remoteRef:
      key: kv/artifactory
      property: master-key
  - secretKey: join-key
    remoteRef:
      key: kv/artifactory
      property: join-key
