apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- externalsecrets.yaml
- namespace.yaml
helmGlobals:
  chartHome: ./
helmCharts:
- name: prometheus-msteams
  version: 1.3.4
  releaseName: prometheus-msteams
  namespace: alerting
