apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  labels:
    app.kubernetes.io/instance: uat-confluent-kafka-nonpci-appdb
  name: kafka
  namespace: confluent-kafka
spec:
  dataVolumeCapacity: 100Gi
  image:
    application: docker.io/confluentinc/cp-server:7.4.0
    init: docker.io/confluentinc/confluent-init-container:2.6.0
  listeners:
    custom:
    - externalAccess:
        route:
          bootstrapPrefix: kafka
          domain: apps.uat-nonpci-appdb.npnbank.local
        type: route
      name: ext-route
      port: 9093
      tls:
        enabled: true
  metricReporter:
    enabled: true
  podTemplate:
    podSecurityContext: {}
    resources:
      requests:
        cpu: '1'
        memory: 4Gi
      limits:
        cpu: "1"
        memory: "16Gi"
  replicas: 3
  tls:
    ignoreTrustStoreConfig: true
    secretRef: kafka-tls
