apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: confluent
    istio-injection: disabled
  name: confluent
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: confluent-kafka
    istio-injection: disabled
  name: confluent-kafka
