apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: router-certs-pca
  namespace: service-mesh
spec:
  data:
  - secretKey: ca.crt
    remoteRef:
      key: alpha/uat-nonpci-appdb/certificate
      property: ca.crt
  - secretKey: tls.crt
    remoteRef:
      key: alpha/uat-nonpci-appdb/certificate
      property: tls.crt
  - secretKey: tls.key
    remoteRef:
      key: alpha/uat-nonpci-appdb/certificate
      property: tls.key
