apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: san-sandbox-camunda-platform
  namespace: argocd
  labels:
    environment: san-sandbox
    component: sharedservices
spec:
  destination:
    name: |
      san-sandbox
    namespace: camunda
  project: croatia-digital-platform
  source:
    path: tactical/camunda-platform
    repoURL: ssh://git@bitbucket.projectcroatia.cloud/dig/croatia-components.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true