apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: san-sandbox-keycloak
  namespace: argocd
  labels:
    environment: san-sandbox
    component: sharedservices
spec:
  destination:
    name: |
      san-sandbox
  project: croatia-digital-platform
  source:
    path: tactical/keycloak
    repoURL: ssh://git@bitbucket.projectcroatia.cloud/dig/croatia-components.git
    targetRevision: HEAD
  syncPolicy: {}
