apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../confluent
patchesStrategicMerge:
- connect.yaml
- kafka.yaml
- kafkarestproxy.yaml
- ksqldb.yaml
- schemaregistry.yaml
- zookeeper.yaml