apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- fluentd-cm.yaml
- telegraf-cm.yaml
helmCharts:
- name: vault
  repo: https://artifactory.apps.prod-nonpci-shared.nrapp.cloud/artifactory/helm-virtual/
  version: 0.27.0
  releaseName: vault-dr
  namespace: vault
  valuesFile: values.yaml