apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-ent
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: development
          role: alpha
          serviceAccountRef:
            name: vault-auth
            namespace: vault
      caProvider:
        key: ca.crt
        name: vault-cert
        namespace: vault
        type: Secret
      namespace: microservices
      path: alpha
      server: 'https://vault-ent.apps.dev-nonpci-shared.npnbank.local/'
      version: v2