apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: confluent
  namespace: argocd-2-12-3
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            argo-cluster-type: alpha
            argo-cluster-role: primary
  template:
    metadata:
      name: '{{nameNormalized}}-confluent'
      namespace: argocd-2-12-3
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
      labels:
        environment: '{{nameNormalized}}'
        component: alpha
    spec:
      destination:
        server: '{{server}}'
      project: croatia-digital-platform
      source:
        path: 'overlays/{{nameNormalized}}/confluent'
        repoURL: 'ssh://git@bitbucket.projectcroatia.cloud/dig/croatia-components.git'
        targetRevision: HEAD