apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vault-client
  namespace: argocd-2-12-3
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            argo-cluster-type: alpha
            argo-cluster-role: primary
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            argo-cluster-type: dmz
            argo-cluster-role: primary
  template:
    metadata:
      name: '{{nameNormalized}}-vault-client'
      namespace: argocd-2-12-3
      labels:
        environment: '{{nameNormalized}}'
        component: alpha
    spec:
      destination:
        server: '{{server}}'
      project: croatia-digital-platform
      source:
        path: 'overlays/{{ nameNormalized }}/vault-client'
        repoURL: 'ssh://git@bitbucket.projectcroatia.cloud/dig/croatia-vault-client.git'
        targetRevision: HEAD