apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
helmCharts:
- name: redis
  repo: https://artifactory.apps.prod-nonpci-shared.nrapp.cloud/artifactory/helm/redis/
  version: 17.9.2
  releaseName: redis
  namespace: redis
  valuesFile: values.yaml
