apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: argocd
  labels:
    component: sharedservices
spec:
  destination:
    namespace: argocd
    server: https://api.prod-nonpci-shared.nrapp.cloud:6443
  project: prod-croatia-digital-platform
  source:
    path: ./
    repoURL: ssh://git@bitbucket.nrapp.cloud/dig/prod-croatia-argocd.git
    targetRevision: HEAD