apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-croatia-operator-dmz-ingress
  namespace: argocd
spec:
  destination:
    namespace: openshit-operators
    server: https://api.prod-dmz-ingress.nrapp.cloud:6443
  project: prod-croatia-digital-platform
  source:
    path: dmz-ingress
    repoURL: ssh://git@bitbucket.nrapp.cloud/dig/prod-croatia-operators.git
    targetRevision: HEAD
