apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dr-nonpci-appdb-vault
  namespace: argocd
spec:
  project: dr-croatia-digital-platform
  source:
    repoURL: 'ssh://git@bitbucket.nrapp.cloud/dig/dr-croatia-components.git'
    path: vault-enterprise
    targetRevision: HEAD
  destination:
    server: 'https://api.dr-nonpci-appdb.nbank.local:6443'
    namespace: vault