apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bitbucket
  namespace: argocd
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: bitbucket
  data:
  - secretKey: bitbucket-token
    remoteRef:
      key: shared/jenkins-credentials
      property: bitbucket-token
