apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-confluent-kafka
  namespace: argocd
spec:
  destination:
    namespace: confluent-kafka
    server: https://api.prod-nonpci-appdb.nrapp.cloud:6443
  project: prod-croatia-digital-platform
  source:
    path: confluent
    repoURL: ssh://git@bitbucket.nrapp.cloud/dig/prod-croatia-confluent-kafka.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true