apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- nonpci-appdb-operators.yaml
- nonpci-shared-operators.yaml
- dmz-ingress-operators.yaml
- alpha-apigateway.yaml
- redis.yaml
- kafka.yaml
- croatia-configuration.yaml
- camunda-platform.yaml
- central-logging.yaml
- dmz-ingress-vault-client.yaml
- nonpci-appdb-vault-client.yaml
- service-mesh.yaml
- sso.yaml
- artifactory.yaml
- sonarqube.yaml
- jenkins.yaml
- alpha-microservices.yaml
- external-secret.yaml
- dr-nonpci-appdb-artifactory.yaml
- dr-nonpci-appdb-camunda-platform.yaml
- dr-nonpci-appdb-confluent-kafka.yaml
- dr-nonpci-appdb-operators.yaml
- dr-nonpci-appdb-vault-client.yaml
- dr-nonpci-appdb-vault.yaml
- dr-alpha-microservices.yaml
- unleash.yaml
- unleash-be.yaml
- n8n.yaml
