apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-nonpci-appdb-vault-client
  namespace: argocd
spec:
  destination:
    namespace: vault
    server: https://api.prod-nonpci-appdb.nrapp.cloud:6443
  project: prod-croatia-digital-platform
  source:
    path: overlays/prod-nonpci-appdb
    repoURL: ssh://git@bitbucket.nrapp.cloud/dig/prod-croatia-vault-client.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
