apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: marketplace
spec:
  data:
    - secretKey: sl-marketplace-client-secret
      remoteRef:
        key: alpha/nft-nonpci-appdb/marketplace
        property: secret
    - secretKey: fob-private-key
      remoteRef:
        key: alpha/nft-nonpci-appdb/marketplace
        property: fob-private-key
    - secretKey: fob-public-key
      remoteRef:
        key: alpha/nft-nonpci-appdb/marketplace
        property: fob-public-key
    - secretKey: key-store-password
      remoteRef:
        key: alpha/nft-nonpci-appdb/marketplace
        property: key-store-password
    - secretKey: trust-store-password
      remoteRef:
        key: alpha/nft-nonpci-appdb/marketplace
        property: trust-store-password
    - secretKey: sl-marketplace-yakeen-client-secret
      remoteRef:
        key: alpha/nft-nonpci-appdb/marketplace
        property: yakeen-secret