apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: temenos
spec:
  data:
    - secretKey: password
      remoteRef:
        key: alpha/nft-nonpci-appdb/temenos
        property: password