apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: t2
spec:
  data:
    - secretKey: password
      remoteRef:
        key: alpha/nft-nonpci-appdb/t2
        property: password
