apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ais
spec:
  data:
    - secretKey: ais-private-key
      remoteRef:
        key: alpha/nft-nonpci-appdb/ais
        property: ais-private-key
    - secretKey: ais-jwe-key
      remoteRef:
        key: alpha/nft-nonpci-appdb/ais
        property: ais-jwe-key