apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crm
spec:
  data:
  - secretKey: mc-crm-adapter-password
    remoteRef:
      key: alpha/sit-nonpci-appdb/crm
      property: mc-crm-adapter-password
