apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentication
spec:
  data:
    - secretKey: authentication-public-key
      remoteRef:
        key: alpha/sit-nonpci-appdb/authentication
        property: authentication-public-key
    - secretKey: authentication-private-key
      remoteRef:
        key: alpha/sit-nonpci-appdb/authentication
        property: authentication-private-key
    - secretKey: authentication-login-public-key
      remoteRef:
        key: alpha/sit-nonpci-appdb/authentication
        property: authentication-login-public-key
    - secretKey: authentication-login-private-key
      remoteRef:
        key: alpha/sit-nonpci-appdb/authentication
        property: authentication-login-private-key
    - secretKey: authentication-jwe-key
      remoteRef:
        key: alpha/sit-nonpci-appdb/authentication
        property: authentication-jwe-key