apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: treasury
spec:
  data:
    - secretKey: treasury-private-key
      remoteRef:
        key: alpha/sit-nonpci-appdb/treasury
        property: treasury-private-key
    - secretKey: treasury-client-secret
      remoteRef:
        key: alpha/sit-nonpci-appdb/treasury
        property: treasury-client-secret