apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ibmisva
spec:
  data:
  - secretKey: isvaUserSecret
    remoteRef:
      key: alpha/sit-nonpci-appdb/ibmisva
      property: isvaUserSecret

  - secretKey: isvaAdminSecret
    remoteRef:
      key: alpha/sit-nonpci-appdb/ibmisva
      property: isvaAdminSecret
