apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: anghami
spec:
  data:
    - secretKey: anghami-client-password
      remoteRef:
        key: alpha/sit-nonpci-appdb/anghami
        property: anghami-client-password
