apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: amq
spec:
  data:
  - secretKey: password
    remoteRef:
      key: alpha/sit-nonpci-appdb/amq
      property: password
  - secretKey: truststore-password
    remoteRef:
      key: alpha/sit-nonpci-appdb/amq
      property: truststore-password
  - secretKey: username
    remoteRef:
      key: alpha/sit-nonpci-appdb/amq
      property: username