apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ob
spec:
  data:
    - secretKey: ob-private-key
      remoteRef:
        key: alpha/sit-nonpci-appdb/ob
        property: ob-private-key
    - secretKey: ob-public-key
      remoteRef:
        key: alpha/sit-nonpci-appdb/ob
        property: ob-public-key
    - secretKey: ob-jwe-key
      remoteRef:
        key: alpha/sit-nonpci-appdb/ob
        property: ob-jwe-key