apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ni
spec:
  data:
    - secretKey: ni-client-secret
      remoteRef:
        key: alpha/sit-nonpci-appdb/ni
        property: ni-client-secret