apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: croatia-configuration
  namespace: argocd
spec:
  generators:
    - merge:
        mergeKeys:
        - nameNormalized
        generators:
        - clusters:
            selector:
              matchLabels:
                argocd.argoproj.io/secret-type: cluster
                argo-cluster-type: alpha
            values:
              targetRevision: 'HEAD'
        - list:
            elements:
            - nameNormalized: dev-cit
              values.targetRevision: 'release/v1'
  template:
    metadata:
      name: '{{nameNormalized}}-configuration'
      namespace: argocd
      labels:
        environment: '{{nameNormalized}}'
        component: alpha
    spec:
      destination:
        server: '{{server}}'
        namespace: alpha
      project: croatia-digital-platform
      source:
        path: 'overlays/{{ nameNormalized }}'
        repoURL: 'ssh://git@bitbucket.projectcroatia.cloud/dig/croatia-configuration.git'
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
