---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-nonpci-shared-backstage
  namespace: argocd
  labels:
    environment: dev-nonpci-shared
    component: sharedservices
spec:
  destination:
    name: |
      dev-nonpci-shared
    namespace: backstage
  project: croatia-digital-platform
  source:
    path: backstage
    repoURL: ssh://git@bitbucket.projectcroatia.cloud/dig/croatia-components.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
