apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  dev-nonpci-shared-nexus-repository
  namespace: argocd
  labels:
    environment: dev-nonpci-shared
    component: sharedservices
spec:
  destination:
    name: |
      dev-nonpci-shared
    namespace: nexus-repository
  project: croatia-digital-platform
  source:
    path: nexus-repository-manager
    repoURL: ssh://git@bitbucket.projectcroatia.cloud/dig/croatia-components.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - Prune=false
    - Delete=false