apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sharedservices
  namespace: argocd
  labels:
    component: sharedservices
spec:
  destination:
    name: |
      dev-nonpci-shared
  project: croatia-digital-platform
  source:
    path: argocd-sharedservices
    repoURL: ssh://git@bitbucket.projectcroatia.cloud/dig/croatia-argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
