apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unleash
  namespace: argocd
spec:
  destination:
    namespace: unleash
    server: 'https://api.dev-nonpci-shared.npnbank.local:6443'
  source:
    path: unleash
    repoURL: 'ssh://git@bitbucket.projectcroatia.cloud/dig/croatia-components.git'
    targetRevision: main
  syncPolicy:
    syncOptions:
      - Prune=false
      - Validate=true
      - SkipDryRunOnMissingResource=false
      - Delete=false
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - PruneLast=false
      - Replace=false
      - ServerSideApply=false
      - FailOnSharedResource=false
      - RespectIgnoreDifferences=false
      - CreateNamespace=false
  project: croatia-digital-platform
