apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '5'
  name: router-certs-pca
  namespace: service-mesh
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: alpha/prod-nonpci-appdb/certificate
        metadataPolicy: None
        property: ca.crt
      secretKey: ca.crt
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: alpha/prod-nonpci-appdb/certificate
        metadataPolicy: None
        property: tls.crt
      secretKey: tls.crt
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: alpha/prod-nonpci-appdb/certificate
        metadataPolicy: None
        property: tls.key
      secretKey: tls.key
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: router-certs-pca
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: kubernetes.io/tls