---
apiVersion: "logging.openshift.io/v1"
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  outputs:
   - name: elasticsearch
     type: "elasticsearch"
     url: https://elasticsearch-logging.apps.san-sandbox.projectcroatia.cloud:443
     secret:
        name: collector
     tls:
       insecureSkipVerify: true
  pipelines:
   - name: infrastructure
     inputRefs:
      - infrastructure
     outputRefs:
      - elasticsearch
     labels:
       environment: '{{ cluster }}'
   - inputRefs:
      - application
     outputRefs:
      - elasticsearch
     labels:
       environment: '{{ cluster }}'
