apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: central-logging-elasticsearch
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: collector
  data:
  - secretKey: tls.crt
    remoteRef:
      key: alpha/openshift-logging-collector
      property: tls.crt
      decodingStrategy: Base64
  - secretKey: tls.key
    remoteRef:
      key: alpha/openshift-logging-collector
      property: tls.key
      decodingStrategy: Base64
  - secretKey: ca-bundle.crt
    remoteRef:
      key: alpha/openshift-logging-collector
      property: ca-bundle.crt
      decodingStrategy: Base64
