apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: otp
spec:
  data:
  - secretKey: otp-code-encoding-key
    remoteRef:
      key: alpha/dev-cit/otp
      property: otp-code-encoding-key
  - secretKey: otp-correlationId-encoding-key
    remoteRef:
      key: alpha/dev-cit/otp
      property: otp-correlationId-encoding-key