apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nafath
spec:
  data:
  - secretKey: nafath-client-secret
    remoteRef:
      key: alpha/dev-cit/nafath
      property: nafath-client-secret
