apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: camunda
spec:
  data:
  - secretKey: operate-client-secret
    remoteRef:
      key: alpha/dev-cit/camunda
      property: operate-client-secret
  - secretKey: tasklist-client-secret
    remoteRef:
      key: alpha/dev-cit/camunda
      property: tasklist-client-secret