apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
- ../primary
patchesStrategicMerge:
- ../mocks/mock-authorization-policies.yaml
- ../swagger/swagger-authorization-policies.yaml
- ingress-authorization-policies.yaml
- configmap.yaml
- externalsecrets.yaml
- externalsecrets-otp.yaml
- externalsecrets-focal.yaml
- externalsecrets-crm.yaml
- externalsecrets-isva.yaml
- externalsecrets-nafath.yaml
- externalsecrets-camunda.yaml
- externalsecrets-temenos.yaml