apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sharedservices
  namespace: argocd-2-12-3
  labels:
    component: sharedservices
spec:
  destination:
    name: |
      dev-nonpci-shared
  project: croatia-digital-platform
  source:
    path: argocd/argocd-sharedservices
    repoURL: ssh://git@bitbucket.projectcroatia.cloud/dig/croatia-componenets.git
    targetRevision: HEAD