apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-nonpci-shared-vault
  namespace: argocd-2-12-3
  labels:
    environment: dev-nonpci-shared
    component: sharedservices
spec:
  destination:
    name: |
      dev-nonpci-shared
    namespace: vault
  project: croatia-digital-platform
  source:
    path: vault
    repoURL: ssh://git@bitbucket.projectcroatia.cloud/dig/croatia-components.git
    targetRevision: HEAD
  syncPolicy: {}