apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- service-mesh.yaml
helmCharts:
- name: sonarqube
  repo: https://SonarSource.github.io/helm-chart-sonarqube
  version: 8.0.0
  releaseName: sonarqube
  namespace: sonarqube
  valuesFile: values.yaml
patchesStrategicMerge:
- statefulset.yaml