apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: sonarqube
    istio-injection: disabled
  name: sonarqube
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
---
kind: ServiceMeshMember
apiVersion: maistra.io/v1
metadata:
  name: default
  namespace: sonarqube
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  controlPlaneRef:
    name: basic
    namespace: service-mesh
