apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-app-config
  namespace: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: backstage-app-config
  data:
  - secretKey: app-config.production.yaml
    remoteRef:
      key: kv/backstage-app-config
      property: app-config.production.yaml
