kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backstage
  namespace: backstage
subjects:
  - kind: ServiceAccount
    name: backstage
roleRef:
  kind: Role
  name: backstage
  apiGroup: rbac.authorization.k8s.io