apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-postgres
  namespace: n8n
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: postgres-password
  data:
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: n8n
      property: postgres-password
