---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: elasticsearch-passthrough
spec:
  host: elasticsearch-logging.apps.san-sandbox.projectcroatia.cloud 
  tls:
    termination: passthrough 
    insecureEdgeTerminationPolicy: None 
  to:
    kind: Service
    name: elasticsearch
    weight: 100
