apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: camunda-platform
    istio-injection: disabled
  name: camunda
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
kind: ServiceMeshMember
apiVersion: maistra.io/v1
metadata:
  name: default
  namespace: camunda
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  controlPlaneRef:
    name: basic
    namespace: service-mesh
