apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- role.yaml
- route.yaml
- sonarqube-svc-headless.yaml
helmCharts:
- name: sonarqube
  namespace: sonarqube
  releaseName: sonarqube
  repo: https://artifactory.apps.prod-nonpci-shared.nrapp.cloud/artifactory/helm/sonarqube/
  valuesFile: values.yaml
  version: 8.0.0
patches:
- path: postgresql-statefulset.yaml
- path: sonarqube-statefulset.yaml
