apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/confluent-for-kubernetes.openshift-operators: ""
  name: confluent-for-kubernetes
  namespace: confluent-kafka
spec:
  channel: "2.7"
  installPlanApproval: Manual
  name: confluent-for-kubernetes
  source: certified-operators
  sourceNamespace: openshift-marketplace
