apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-admin
  namespace: jenkins
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: jenkins-admin
  data:
  - secretKey: jenkins-admin-password
    remoteRef:
      key: shared/jenkins-admin
      property: jenkins-admin-password
  - secretKey: jenkins-admin-user
    remoteRef:
      key: shared/jenkins-admin
      property: jenkins-admin-user
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-credentials
  namespace: jenkins
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: jenkins-credentials
  data:
  - secretKey: admin-password
    remoteRef:
      key: shared/jenkins-credentials
      property: admin-password
  - secretKey: bitbucket-token
    remoteRef:
      key: shared/jenkins-credentials
      property: bitbucket-token
  - secretKey: sonar-token
    remoteRef:
      key: shared/jenkins-credentials
      property: sonar-token
  - secretKey: ssh-key
    remoteRef:
      key: shared/jenkins-credentials
      property: ssh-key
  - secretKey: openid-client-secret
    remoteRef:
      key: shared/jenkins-credentials
      property: openid-client-secret
  - secretKey: vault-token
    remoteRef:
      key: shared/jenkins-credentials
      property: vault-token
  - secretKey: smtp-user
    remoteRef:
      key: shared/jenkins-credentials
      property: smtp-user
  - secretKey: smtp-pass
    remoteRef:
      key: shared/jenkins-credentials
      property: smtp-pass
  - secretKey: jira-token
    remoteRef:
      key: shared/jenkins-credentials
      property: jira-token
  - secretKey: artifactory-username
    remoteRef:
      key: shared/jenkins-credentials
      property: artifactory-username
  - secretKey: artifactory-password
    remoteRef:
      key: shared/jenkins-credentials
      property: artifactory-password
  - secretKey: artifactory-docker
    remoteRef:
      key: shared/jenkins-credentials
      property: artifactory-docker
  - secretKey: prod-nonpci-appdb-deployment-token
    remoteRef:
      key: shared/clusters
      property: prod-nonpci-appdb-deployment-token
  - secretKey: prod-nonpci-shared-deployment-token
    remoteRef:
      key: shared/clusters
      property: prod-nonpci-shared-deployment-token
  - secretKey: prod-pci-appdb-deployment-token
    remoteRef:
      key: shared/clusters
      property: prod-pci-appdb-deployment-token
  - secretKey: prod-dmz-ingress-deployment-token
    remoteRef:
      key: shared/clusters
      property: prod-dmz-ingress-deployment-token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-mobile
  namespace: jenkins
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: jenkins-mobile
  data:
  - secretKey: android-keystore
    remoteRef:
      key: shared/jenkins-mobile
      property: android-keystore
  - secretKey: android-keystore-password
    remoteRef:
      key: shared/jenkins-mobile
      property: android-keystore-password
  - secretKey: meawallet-username
    remoteRef:
      key: shared/jenkins-mobile
      property: meawallet-username
  - secretKey: meawallet-password
    remoteRef:
      key: shared/jenkins-mobile
      property: meawallet-password
  - secretKey: api-token-prod
    remoteRef:
      key: shared/jenkins-mobile
      property: api-token-prod
  - secretKey: appsflyer-key-prod
    remoteRef:
      key: shared/jenkins-mobile
      property: appsflyer-key-prod
  - secretKey: appsflyer-key-ios-prod
    remoteRef:
      key: shared/jenkins-mobile
      property: appsflyer-key-ios-prod
  - secretKey: android-appcenter-api-token
    remoteRef:
      key: shared/jenkins-mobile
      property: android-appcenter-api-token
  - secretKey: ios-appcenter-api-token
    remoteRef:
      key: shared/jenkins-mobile
      property: ios-appcenter-api-token
