apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
# - machineset.yaml
- role.yaml
- agent-serviceaccount.yaml
- route.yaml
- externalsecrets.yaml
- sso.yaml
helmCharts:
- name: jenkins
  repo: https://artifactory.apps.prod-nonpci-shared.nrapp.cloud/artifactory/helm-virtual/jenkins/
  version: 4.3.22
  releaseName: jenkins
  namespace: jenkins
  valuesFile: values.yaml
