apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: jenkins
  namespace: sso
spec:
  instanceSelector:
    matchLabels:
      app: sso
  realm:
    displayName: jenkins
    enabled: true
    id: jenkins
    realm: jenkins