apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-admin
  namespace: jenkins
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: jenkins-admin
  data:
  - secretKey: jenkins-admin-password
    remoteRef:
      key: shared/jenkins-admin
      property: jenkins-admin-password
  - secretKey: jenkins-admin-user
    remoteRef:
      key: shared/jenkins-admin
      property: jenkins-admin-user
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-credentials
  namespace: jenkins
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: jenkins-credentials
  data:
  - secretKey: admin-password
    remoteRef:
      key: shared/jenkins-credentials
      property: admin-password
  - secretKey: bitbucket-token
    remoteRef:
      key: shared/jenkins-credentials
      property: bitbucket-token
  - secretKey: sonar-token
    remoteRef:
      key: shared/jenkins-credentials
      property: sonar-token
  - secretKey: sonar-new-token
    remoteRef:
      key: shared/jenkins-credentials
      property: sonar-new-token
  - secretKey: ssh-key
    remoteRef:
      key: shared/jenkins-credentials
      property: ssh-key
  - secretKey: oci-key
    remoteRef:
      key: shared/jenkins-credentials
      property: oci-key
  - secretKey: oci-config
    remoteRef:
      key: shared/jenkins-credentials
      property: oci-config
  - secretKey: openid-client-secret
    remoteRef:
      key: shared/jenkins-credentials
      property: openid-client-secret
  - secretKey: vault-token
    remoteRef:
      key: shared/jenkins-credentials
      property: vault-token
  - secretKey: smtp-user
    remoteRef:
      key: shared/jenkins-credentials
      property: smtp-user
  - secretKey: smtp-pass
    remoteRef:
      key: shared/jenkins-credentials
      property: smtp-pass
  - secretKey: jira-token
    remoteRef:
      key: shared/jenkins-credentials
      property: jira-token
  - secretKey: artifactory-username
    remoteRef:
      key: shared/jenkins-credentials
      property: artifactory-username
  - secretKey: artifactory-password
    remoteRef:
      key: shared/jenkins-credentials
      property: artifactory-password
  - secretKey: artifactory-docker
    remoteRef:
      key: shared/jenkins-credentials
      property: artifactory-docker
  - secretKey: vm-ssh-credentials-id 
    remoteRef:
      key: shared/jenkins-credentials
      property: vm-ssh-credentials-id 
  - secretKey: dev-dmz-ingress-deployment-token
    remoteRef:
      key: shared/clusters
      property: dev-dmz-ingress-deployment-token
  - secretKey: dev-nonpci-appdb-deployment-token
    remoteRef:
      key: shared/clusters
      property: dev-nonpci-appdb-deployment-token
  - secretKey: dev-nonpci-shared-deployment-token
    remoteRef:
      key: shared/clusters
      property: dev-nonpci-shared-deployment-token
  - secretKey: dev-pci-appdb-deployment-token
    remoteRef:
      key: shared/clusters
      property: dev-pci-appdb-deployment-token
  - secretKey: sit-dmz-ingress-deployment-token
    remoteRef:
      key: shared/clusters
      property: sit-dmz-ingress-deployment-token
  - secretKey: sit-nonpci-appdb-deployment-token
    remoteRef:
      key: shared/clusters
      property: sit-nonpci-appdb-deployment-token
  - secretKey: sit-pci-appdb-deployment-token
    remoteRef:
      key: shared/clusters
      property: sit-pci-appdb-deployment-token
  - secretKey: uat-dmz-ingress-deployment-token
    remoteRef:
      key: shared/clusters
      property: uat-dmz-ingress-deployment-token
  - secretKey: uat-nonpci-appdb-deployment-token
    remoteRef:
      key: shared/clusters
      property: uat-nonpci-appdb-deployment-token
  - secretKey: uat-pci-appdb-deployment-token
    remoteRef:
      key: shared/clusters
      property: uat-pci-appdb-deployment-token
  - secretKey: nft-dmz-ingress-deployment-token
    remoteRef:
      key: shared/clusters
      property: nft-dmz-ingress-deployment-token
  - secretKey: nft-nonpci-appdb-deployment-token
    remoteRef:
      key: shared/clusters
      property: nft-nonpci-appdb-deployment-token
  - secretKey: nft-pci-appdb-deployment-token
    remoteRef:
      key: shared/clusters
      property: nft-pci-appdb-deployment-token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-mobile
  namespace: jenkins
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: jenkins-mobile
  data:
  - secretKey: android-keystore
    remoteRef:
      key: shared/jenkins-mobile
      property: android-keystore
  - secretKey: android-keystore-password
    remoteRef:
      key: shared/jenkins-mobile
      property: android-keystore-password
  - secretKey: meawallet-username
    remoteRef:
      key: shared/jenkins-mobile
      property: meawallet-username
  - secretKey: meawallet-password
    remoteRef:
      key: shared/jenkins-mobile
      property: meawallet-password
  - secretKey: api-token-dev
    remoteRef:
      key: shared/jenkins-mobile
      property: api-token-dev
  - secretKey: appsflyer-key-dev
    remoteRef:
      key: shared/jenkins-mobile
      property: appsflyer-key-dev
  - secretKey: appsflyer-key-ios-dev
    remoteRef:
      key: shared/jenkins-mobile
      property: appsflyer-key-ios-dev
  - secretKey: android-appcenter-api-token
    remoteRef:
      key: shared/jenkins-mobile
      property: android-appcenter-api-token
  - secretKey: ios-appcenter-api-token
    remoteRef:
      key: shared/jenkins-mobile
      property: ios-appcenter-api-token
