apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    machine.openshift.io/memoryMb: '16384'
    machine.openshift.io/vCPU: '4'
    argocd.argoproj.io/sync-wave: "-1"
  name: jenkins-workers
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: dev-nonpci-shared-5f9mm
    service: jenkins-agents
spec:
  replicas: 5
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: dev-nonpci-shared-5f9mm
      machine.openshift.io/cluster-api-machineset: jenkins-workers
  template:
    metadata:
      labels:
        croatia-role: jenkins
        machine.openshift.io/cluster-api-cluster: dev-nonpci-shared-5f9mm
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: jenkins-workers
    spec:
      lifecycleHooks: {}
      metadata:
        labels:
          croatia-role: jenkins
      providerSpec:
        value:
          numCoresPerSocket: 1
          diskGiB: 120
          snapshot: ''
          userDataSecret:
            name: worker-user-data
          memoryMiB: 16384
          credentialsSecret:
            name: vsphere-cloud-credentials
          network:
            devices:
              - networkName: NSX-SEG-NonProd-NonPCI-Shared
          metadata:
            creationTimestamp: null
          numCPUs: 4
          kind: VSphereMachineProviderSpec
          workspace:
            datacenter: OCI-DigitalPlatform
            datastore: vsanDatastore-NonPCI
            folder: /OCI-DigitalPlatform/vm/dev-nonpci-shared-5f9mm
            resourcePool: >-
              /OCI-DigitalPlatform/host/DigitalPlatform_NonPCI_VMware_Cluster/Resources
            server: vcenter-nonproddpsddc.sddc.jed.oci.oraclecloud.com
          template: dev-nonpci-shared-5f9mm-rhcos
          apiVersion: machine.openshift.io/v1beta1
      taints:
      - effect: NoSchedule
        key: service
        value: jenkins-agents