apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: confluent
    istio-injection: disabled
  name: confluent
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    openshift.io/sa.scc.mcs: "s0:c27,c19"
    openshift.io/sa.scc.supplemental-groups: "1000980000/10000"
    openshift.io/sa.scc.uid-range: "1000980000/10000"
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: confluent-kafka
    istio-injection: disabled
  name: confluent-kafka
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    openshift.io/sa.scc.mcs: "s0:c27,c19"
    openshift.io/sa.scc.supplemental-groups: "1000980000/10000"
    openshift.io/sa.scc.uid-range: "1000980000/10000"
