apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper
  namespace: confluent-kafka
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 3
  image:
    application: docker.io/confluentinc/cp-zookeeper:7.3.0
    init: docker.io/confluentinc/confluent-init-container:2.5.0
  dataVolumeCapacity: 100Gi
  logVolumeCapacity: 100Gi
  podTemplate:
    podSecurityContext: {}
