apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-ent
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: nft-nonpci-appdb
          role: alpha
      caProvider:
        key: ca.crt
        name: vault-ca-cert
        namespace: vault
        type: Secret
      namespace: microservices
      path: alpha