apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cacertificate.yaml
- namespace.yaml
- serviceaccount.yaml
- clusterrolebinding.yaml
- clustersecretstore.yaml
- operatorconfig.yaml
