apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: router-certs-sonar
  namespace: sonarqube
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: router-certs-sonar
    template:
      type: kubernetes.io/tls
  data:
  - secretKey: ca.crt
    remoteRef:
      key: shared/certificate
      property: ca.crt

