apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:./argocd
  title: ArgoCD
  name: argocd
spec:
  lifecycle: experimental
  owner: platform
  type: service
  system: croatia-shared-services
