apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: argocd
  namespace: sso
spec:
  instanceSelector:
    matchLabels:
      app: sso
  realm:
    displayName: argocd
    enabled: true
    id: argocd
    realm: argocd
