---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: bitbucket
  name: postgres-data
  labels:
    app.kubernetes.io/name: postgres
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
