apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ob
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: ob
  data:
    - secretKey: ob-private-key
      remoteRef:
        key: alpha/placeholder/ob
        property: ob-private-key
    - secretKey: ob-public-key
      remoteRef:
        key: alpha/placeholder/ob
        property: ob-public-key
    - secretKey: ob-jwe-key
      remoteRef:
        key: alpha/placeholder/ob
        property: ob-jwe-key