apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: treasury
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: treasury
  data:
    - secretKey: treasury-private-key
      remoteRef:
        key: alpha/placeholder/treasury
        property: treasury-private-key
    - secretKey: treasury-client-secret
      remoteRef:
        key: alpha/placeholder/treasury
        property: treasury-client-secret