apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: drahim
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: drahim
  data:
    - secretKey: drahim-client-secret
      remoteRef:
        key: alpha/placeholder/drahim
        property: secret