apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: database
  data:
  - secretKey: mc-password
    remoteRef:
      key: alpha/development/database
      property: mc-password
  - secretKey: sc-password
    remoteRef:
      key: alpha/development/database
      property: sc-password
  - secretKey: sl-password
    remoteRef:
      key: alpha/development/database
      property: sl-password
