apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: arb
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: arb
  data:
  - secretKey: arb-private-key
    remoteRef:
      key: alpha/development/arb
      property: arb-private-key
