apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ais
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: ais
  data:
    - secretKey: ais-private-key
      remoteRef:
        key: alpha/placeholder/ais
        property: ais-private-key
    - secretKey: ais-jwe-key
      remoteRef:
        key: alpha/placeholder/ais
        property: ais-jwe-key