apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentication
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: authentication
  data:
    - secretKey: authentication-public-key
      remoteRef:
        key: alpha/placeholder/authentication
        property: authentication-public-key
    - secretKey: authentication-private-key
      remoteRef:
        key: alpha/placeholder/authentication
        property: authentication-private-key
    - secretKey: authentication-login-public-key
      remoteRef:
        key: alpha/placeholder/authentication
        property: authentication-login-public-key
    - secretKey: authentication-login-private-key
      remoteRef:
        key: alpha/placeholder/authentication
        property: authentication-login-private-key
    - secretKey: authentication-jwe-key
      remoteRef:
        key: alpha/placeholder/authentication
        property: authentication-jwe-key