apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ibmisva
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: ibmisva
  data:
  - secretKey: isvaUserSecret
    remoteRef:
      key: alpha/placeholder/ibmisva
      property: isvaUserSecret
  - secretKey: isvaAdminSecret
    remoteRef:
      key: alpha/placeholder/ibmisva
      property: isvaAdminSecret
