apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: neotek
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: neotek
  data:
  - secretKey: neotek-client-secret
    remoteRef:
      key: alpha/placeholder/neotek
      property: neotek-client-secret
  - secretKey: neotek-key-store-password
    remoteRef:
      key: alpha/placeholder/neotek
      property: neotek-key-store-password
  - secretKey: neotek-trust-store-password
    remoteRef:
      key: alpha/placeholder/neotek
      property: neotek-trust-store-password