apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: otp
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: otp
  data:
  - secretKey: otp-code-encoding-key
    remoteRef:
      key: alpha/development/otp
      property: otp-code-encoding-key
  - secretKey: otp-correlationId-encoding-key
    remoteRef:
      key: alpha/development/otp
      property: otp-correlationId-encoding-key
