apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: anghami
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: anghami
  data:
    - secretKey: anghami-client-password
      remoteRef:
        key: alpha/dev-nonpci-appdb/anghami
        property: anghami-client-password
