apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: complaint
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: complaint
  data:
    - secretKey: smtp-auth-password
      remoteRef:
        key: alpha/dev-nonpci-appdb/complaint
        property: smtp-auth-password
