apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ni
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: ni
  data:
    - secretKey: ni-client-secret
      remoteRef:
        key: alpha/development/ni
        property: ni-client-secret