apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: t2
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: t2
  data:
    - secretKey: password
      remoteRef:
        key: alpha/development/t2
        property: password