apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: amq
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: amq
  data:
    - secretKey: password
      remoteRef:
        key: alpha/dev-nonpci-appdb/amq
        property: password
    - secretKey: truststore-password
      remoteRef:
        key: alpha/dev-nonpci-appdb/amq
        property: truststore-password
    - secretKey: username
      remoteRef:
        key: alpha/dev-nonpci-appdb/amq
        property: username
