apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: isva
spec:
  secretStoreRef:
    name: vault-ent
    kind: ClusterSecretStore
  target:
    name: isva
  data:
  - secretKey: clientSecret
    remoteRef:
      key: alpha/placeholder/isva
      property: clientSecret
