apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nafath
spec:
  data:
  - secretKey: nafath-client-secret
    remoteRef:
      key: alpha/prod-nonpci-appdb/nafath
      property: nafath-client-secret
