apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: apple
spec:
  data:
    - secretKey: pass-file-appreciation-password
      remoteRef:
        key: alpha/prod-nonpci-appdb/apple
        property: pass-file-appreciation-password