apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shahid
spec:
  data:
    - secretKey: shahid-client-key
      remoteRef:
        key: alpha/prod-nonpci-appdb/shahid
        property: shahid-client-key