apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: focal
spec:
  data:
  - secretKey: focal-password
    remoteRef:
      key: alpha/prod-nonpci-appdb/focal
      property: focal-password