apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../camunda-platform
#patchesStrategicMerge:
#- route.yaml
#patches:
#- target:
#    kind: Secret
#  patch: |-
#    $patch: delete
#    apiVersion: v1
#    kind: Secret
#    metadata:
#      name: any
