apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: projectcroatia
spec:
  vault:
    auth:
      appRole:
        path: approle
        roleId: placeholder
        secretRef:
          key: secretId
          name: cert-manager-vault-approle
    path: pki_int/sign/dev-shared-services
    server: placeholder
