apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: development
          role: alpha
          serviceAccountRef:
            name: vault-auth
            namespace: vault
      caProvider:
        key: ca.crt
        name: vault-ca-cert
        namespace: vault
        type: Secret
      path: alpha
      server: 'https://vault.ingress.san-sandbox.projectcroatia.cloud/'
      version: v2
