apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: postgresql
    istio-injection: disabled
  name: postgresql
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    argocd.argoproj.io/sync-options: Prune=false
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    olm.providedAPIs: PerconaPGCluster.v1.pg.percona.com,Pgcluster.v1.pg.percona.com,Pgpolicy.v1.pg.percona.com,Pgreplica.v1.pg.percona.com,Pgtask.v1.pg.percona.com
    argocd.argoproj.io/sync-options: Prune=false
  name: postgresql
  namespace: postgresql
spec:
  targetNamespaces:
  - postgresql
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: percona-postgresql-operator
  namespace: postgresql
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: Prune=false
spec:
  channel: stable
  installPlanApproval: Automatic
  name: percona-postgresql-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: percona-postgresql-operator.v1.3.0
