apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: Prune=false
spec:
  provider:
    vault:
      server: https://vault-active.vault.svc.cluster.local:8200
      path: kv
      version: v2
      caProvider:
        key: ca.crt
        name: vault-ca-cert
        namespace: vault
        type: Secret
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
          serviceAccountRef:
            name: vault-auth
            namespace: vault
