apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- certificate.yaml
- service-mesh.yaml
- clusterrolebinding.yaml
- serviceaccount.yaml
- clustersecretstore.yaml
- operatorconfig.yaml
helmCharts:
- name: vault
  repo: https://helm.releases.hashicorp.com
  version: 0.23.0
  releaseName: vault
  namespace: vault
  valuesFile: values.yaml
