apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: sso
    istio-injection: disabled
  name: sso
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: sso
  namespace: sso
spec:
  targetNamespaces:
  - sso
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhsso-operator
  namespace: sso
spec:
  channel: stable
  installPlanApproval: Manual
  name: rhsso-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: rhsso-operator.7.6.6-opr-001

