apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-admin
  namespace: jenkins
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: jenkins-admin
  data:
  - secretKey: jenkins-admin-password
    remoteRef:
      key: kv/jenkins-admin
      property: jenkins-admin-password
  - secretKey: jenkins-admin-user
    remoteRef:
      key: kv/jenkins-admin
      property: jenkins-admin-user
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-credentials
  namespace: jenkins
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: jenkins-credentials
  data:
  - secretKey: admin-password
    remoteRef:
      key: kv/jenkins-credentials
      property: admin-password
  - secretKey: bitbucket-token
    remoteRef:
      key: kv/jenkins-credentials
      property: bitbucket-token
  - secretKey: sonar-token
    remoteRef:
      key: kv/jenkins-credentials
      property: sonar-token
  - secretKey: ssh-key
    remoteRef:
      key: kv/jenkins-credentials
      property: ssh-key
  - secretKey: oci-key
    remoteRef:
      key: kv/jenkins-credentials
      property: oci-key
  - secretKey: oci-config
    remoteRef:
      key: kv/jenkins-credentials
      property: oci-config
  - secretKey: development-kubeconfig
    remoteRef:
      key: kv/jenkins-credentials
      property: development-kubeconfig
  - secretKey: dev-cit-kubeconfig
    remoteRef:
      key: kv/jenkins-credentials
      property: dev-cit-kubeconfig
  - secretKey: openid-client-secret
    remoteRef:
      key: kv/jenkins-credentials
      property: openid-client-secret
  - secretKey: san-sandbox-kubeconfig
    remoteRef:
      key: kv/jenkins-credentials
      property: san-sandbox-kubeconfig
  - secretKey: vault-token
    remoteRef:
      key: kv/jenkins-credentials
      property: vault-token
  - secretKey: smtp-user
    remoteRef:
      key: kv/jenkins-credentials
      property: smtp-user
  - secretKey: smtp-pass
    remoteRef:
      key: kv/jenkins-credentials
      property: smtp-pass
  - secretKey: jira-token
    remoteRef:
      key: kv/jenkins-credentials
      property: jira-token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-mobile
  namespace: jenkins
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: jenkins-mobile
  data:
  - secretKey: android-keystore
    remoteRef:
      key: kv/jenkins-mobile
      property: android-keystore
  - secretKey: android-keystore-password
    remoteRef:
      key: kv/jenkins-mobile
      property: android-keystore-password
  - secretKey: meawallet-username
    remoteRef:
      key: kv/jenkins-mobile
      property: meawallet-username
  - secretKey: meawallet-password
    remoteRef:
      key: kv/jenkins-mobile
      property: meawallet-password
  - secretKey: api-token-dev
    remoteRef:
      key: kv/jenkins-mobile
      property: api-token-dev
  - secretKey: appsflyer-key-dev
    remoteRef:
      key: kv/jenkins-mobile
      property: appsflyer-key-dev
  - secretKey: appsflyer-key-ios-dev
    remoteRef:
      key: kv/jenkins-mobile
      property: appsflyer-key-ios-dev
  - secretKey: android-appcenter-api-token
    remoteRef:
      key: kv/jenkins-mobile
      property: android-appcenter-api-token
  - secretKey: ios-appcenter-api-token
    remoteRef:
      key: kv/jenkins-mobile
      property: ios-appcenter-api-token
