apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- machineset.yaml
- role.yaml
- externalsecrets.yaml
- agent-serviceaccount.yaml
- certificate.yaml
- service-mesh.yaml
helmCharts:
- name: jenkins
  repo: https://charts.jenkins.io
  version: 4.3.22
  releaseName: jenkins
  namespace: jenkins
  valuesFile: values.yaml
