apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: jenkins
    istio-injection: disabled
  name: jenkins
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
---
kind: ServiceMeshMember
apiVersion: maistra.io/v1
metadata:
  name: default
  namespace: jenkins
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  controlPlaneRef:
    name: basic
    namespace: service-mesh
