global:
  enabled: true
  tlsDisable: false
  openshift: true  
  ui:
    enabled: true
server:
  route:
    enabled: true
 
    # When HA mode is enabled and K8s service registration is being used,
    # configure the route to point to the Vault active service.
    activeService: true
 
    labels: {}
    annotations: {}
    host: vault-dev.apps.dev-nonpci-shared.npnbank.local
    # tls will be passed directly to the route's TLS config, which
    # can be used to configure other termination methods that terminate
    # TLS at the router
    tls:
      termination: passthrough 
      insecureEdgeTerminationPolicy: None
  dataStorage:
    enabled: true
    size: 12Gi
  auditStorage:
    enabled: true
    size: 5Gi
  image:
    repository: artifactory.apps.dev-nonpci-shared.npnbank.local/docker-local/hashicorp/vault-enterprise
    tag: 1.15.5-ent
  enterpriseLicense:
    secretName: vault-ent-license
  ha:
    enabled: true
    replicas: 5
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui=true
        log_level = "trace" 
        listener "tcp" {
        tls_disable = 0
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        tls_cert_file = "/vault/userconfig/vault-ha-tls/tls.crt"
        tls_key_file  = "/vault/userconfig/vault-ha-tls/tls.key"
        #tls_client_ca_file = "/vault/userconfig/vault-server-tls/ca.crt"
        }
        storage "raft" {
          path = "/vault/data"
        }
        service_registration "kubernetes" {}    
  extraEnvironmentVars: 
    VAULT_CACERT: /vault/userconfig/vault-ha-tls/ca.crt
  volumes: 
    - name: userconfig-vault-ha-tls 
      secret: 
        defaultMode: 420 
        secretName: vault-ha-tls # Matches the ${SECRET_NAME} from above 
  volumeMounts: 
    - mountPath: /vault/userconfig/vault-ha-tls 
      name: userconfig-vault-ha-tls 
      readOnly: true
injector:
  # image sets the repo and tag of the vault-k8s image to use for the injector.
  image:
    repository: artifactory.apps.dev-nonpci-shared.npnbank.local/docker-local/hashicorp/vault-k8s
    tag: 1.3.1
