# Source: camunda-platform/charts/connectors/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda-platform-connectors
  labels:
    app: camunda-platform
    app.kubernetes.io/name: connectors
    app.kubernetes.io/instance: camunda-platform
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: camunda-platform
    app.kubernetes.io/component: connectors

spec:
  replicas: 1
  selector:
    matchLabels:
      app: camunda-platform
      app.kubernetes.io/name: connectors
      app.kubernetes.io/instance: camunda-platform
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: camunda-platform
      app.kubernetes.io/component: connectors
  template:
    metadata:
      labels:
        app: camunda-platform
        app.kubernetes.io/name: connectors
        app.kubernetes.io/instance: camunda-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: camunda-platform
        app.kubernetes.io/component: connectors
    spec:
      containers:
      - name: connectors
        image: "artifactory.apps.prod-nonpci-shared.nrapp.cloud/docker/camunda/connectors-bundle:0.15.0"
        imagePullPolicy: Always
        env:
          - name: ZEEBE_CLIENT_BROKER_GATEWAY-ADDRESS
            value: "camunda-platform-zeebe-gateway:26500" # Put config
          - name: ZEEBE_CLIENT_SECURITY_PLAINTEXT
            value: "true"
          - name: CAMUNDA_OPERATE_CLIENT_KEYCLOAK-URL
            value: "http://camunda-platform-key:80"
          - name: CAMUNDA_OPERATE_CLIENT_KEYCLOAK-REALM
            value: "camunda-platform"
          - name: CAMUNDA_OPERATE_CLIENT_URL
            value: "http://camunda-platform-operate:80"
          - name: CAMUNDA_CONNECTOR_POLLING_ENABLED
            value: "false"
          - name: CAMUNDA_CONNECTOR_WEBHOOK_ENABLED
            value: "false"
          - name: SPRING_MAIN_WEB-APPLICATION-TYPE
            value: none

        resources:
          limits:
            cpu: 800m
            memory: 1Gi
          requests:
            cpu: 600m
            memory: 400Mi
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /usr/local/connectors/config/application.yml
          subPath: application.yml
      volumes:
      - name: config
        configMap:
          name: camunda-platform-connectors
          defaultMode: 484

