apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- assign-roles.yaml
helmCharts:
- name: camunda-platform
  repo: https://artifactory.apps.prod-nonpci-shared.nrapp.cloud/artifactory/helm-virtual/
  version: 10.3.2
  releaseName: camunda-platform
  namespace: camunda
  valuesFile: values.yaml
patchesStrategicMerge:
- key-statefulset.yaml
- pg-statefulset.yaml
- es-statefulset.yaml
#patches:
#- target:
#    kind: Secret
#  patch: |-
#    $patch: delete
#    apiVersion: v1
#    kind: Secret
#    metadata:
#      name: any

      

