apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: vault
  namespace: sso
spec:
  instanceSelector:
    matchLabels:
      app: sso
  realm:
    displayName: vault
    enabled: true
    id: vault
    realm: vault
