apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: Prune=false
spec:
  provider:
    vault:
      server: https://vault.apps.dev-nonpci-shared.npnbank.local
      path: shared
      version: v2
      caProvider:
        key: ca.crt
        name: vault-cert
        namespace: vault
        type: Secret
      auth:
        kubernetes:
          mountPath: dev-nonpci-shared
          role: dev-nonpci-shared
          serviceAccountRef:
            name: vault-auth
            namespace: vault
