apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: Prune=false
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: postgresql
  data:
  - secretKey: username
    remoteRef:
      key: kv/keycloak-postgresql
      property: username
  - secretKey: password
    remoteRef:
      key: kv/keycloak-postgresql
      property: password
