apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  labels:
    app: sso
  name: keycloak
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  hostname:
    hostname: keycloak.apps.san-sandbox.projectcroatia.cloud
  http:
    tlsSecret: keycloak-cert
  instances: 1
  db:
    database: keycloak
    host: shared-services.postgresql.svc.cluster.local
    passwordSecret:
      key: password
      name: postgresql
    usernameSecret:
      key: username
      name: postgresql
    vendor: postgres
