pipeline {
  agent {
    kubernetes {
      inheritFrom 'infrastructure'
      yaml '''
      spec:
        containers:
        - name: jnlp
          securityContext: 
            privileged: true
            runAsUser: 0
      '''
    }
  }
  environment {
    ARTIFACTORY = credentials('artifactory')
    DOCKER_TOKEN = credentials('artifactory-docker')
    IMAGE_TYPE="${env.IMAGE_TYPE}"
  }
  stages {
    stage('build') {
      steps {
        sh '''
        IMAGE_TAG=$(echo $BRANCH | sed 's,origin/,,g')
        IMAGE_TAG=$(echo $IMAGE_TAG | sed 's,/,-,g')
        IMAGE_TAG=$(echo $IMAGE_TAG | sed 's,\\\\,-,g')
        SHORT_COMMIT=$(echo $GIT_COMMIT |  cut -c 1-7)
        IMAGE_TAG="$IMAGE_TAG-$SHORT_COMMIT"
        cd "jenkins/containers/$IMAGE_TYPE"
        buildah login -u "$ARTIFACTORY_USR" -p "$DOCKER_TOKEN" artifactory.apps.dev-nonpci-shared.npnbank.local
        buildah bud -t "artifactory.apps.dev-nonpci-shared.npnbank.local/docker-local/croatia-${IMAGE_TYPE}-agent:${IMAGE_TAG}" .
        buildah tag "artifactory.apps.dev-nonpci-shared.npnbank.local/docker-local/croatia-${IMAGE_TYPE}-agent:${IMAGE_TAG}" "artifactory.apps.dev-nonpci-shared.npnbank.local/docker-local/croatia-${IMAGE_TYPE}-agent:latest"
        buildah push "artifactory.apps.dev-nonpci-shared.npnbank.local/docker-local/croatia-${IMAGE_TYPE}-agent:${IMAGE_TAG}"
        buildah push "artifactory.apps.dev-nonpci-shared.npnbank.local/docker-local/croatia-${IMAGE_TYPE}-agent:latest"
        '''
      }
    }
  }
}
