---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres
  namespace: bitbucket
  labels:
    app.kubernetes.io/name: postgres
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
data:
  POSTGRES_DB: bitbucket
  POSTGRES_USER: bitbucket
