---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: bitbucket
  name: bitbucket-data
  labels:
    app: bitbucket-data
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
