kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bitbucket
  namespace: bitbucket
subjects:
  - kind: ServiceAccount
    name: bitbucket
roleRef:
  kind: Role
  name: bitbucket
  apiGroup: rbac.authorization.k8s.io