---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres
  namespace: bitbucket
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: postgres
  data:
  - secretKey: POSTGRES_USERNAME
    remoteRef:
      key: shared/bitbucket
      property: postgres-username
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: shared/bitbucket
      property: postgres-password
